[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc="0.8.25"
fs_permissions = [{ access = "read-write", path = "./" }]
remappings = [
    '@openzeppelin-contracts/contracts/=lib/openzeppelin-contracts/contracts',
    'forge-std=lib/forge-std/src/',
    'murky=lib/murky',
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
